sudo: required

dist: trusty
language: go

go:
  -  1.11.x

services:
  - docker

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

notifications:
  email:
    - haystack-notifications@expedia.com