sudo: required

dist: trusty
language: go

go:
  -  1.11.x

services:
  - docker

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - make release

notifications:
  email:
    - haystack-notifications@expedia.com