sudo: required

dist: trusty
language: go

go:
  -  1.11.x

services:
  - docker

env:
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint

install:
  - make release

deploy:
  provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/docker_push.sh && $TRAVIS_BUILD_DIR/docker_push.sh
  on:
    branch: master
    
notifications:
  email:
    - haystack-notifications@expedia.com
