apiVersion: v1
kind: Service
metadata:
  name: kubernetes-sidecar-injector-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: kubernetes-sidecar-injector
