apiVersion: v1
kind: ConfigMap
metadata:
  name: haystack-sidecar-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: haystack-agent
        image: expediadotcom/haystack-agent
        imagePullPolicy: IfNotPresent
        args:
          - --config-provider
          - file
          - --file-path
          - /app/haystack/agent.conf
        ports:
          - containerPort: 35000
        volumeMounts:
          - name: agent-conf
            mountPath: /app/haystack
    volumes:
      - name: agent-conf
        configMap:
          name: haystack-agent-conf-configmap