apiVersion: v1
kind: ConfigMap
metadata:
  name: haystack-agent-conf-configmap
data:
  agent.conf: |
    agents {
      spans {
        enabled = true
        port = 35000
        dispatchers {
          kafka {
            bootstrap.servers = "kafkasvc:9092"
            producerTopic = "proto-spans"
            buffer.memory = 1048576
            retries = 2
          }
        }
      }
    }