# Default values for Haystack kube sidecar intector
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: mageshcmouli/haystack-kube-sidecar-injector
  tag: alpha-20190216080826